# Explicit matrix factorization based on Keras 2

The idea is based on embeddings, as explained by Jeremy Howard of [fast.ai](http://course.fast.ai/lessons/lesson4.html).

The main idea is to apply embeddings to a problem like user-movie ratings (content filtering), by using a matrix decomposition.  The particular method has to be able to deal with missing values in the matrix, so SVD or PCA cannot work here.

The particular inspiration is from a [blog](http://www.albertauyeung.com/post/python-matrix-factorization/), modified to use Keras v2.

The code for the final application is taken from [3rd place winner](https://github.com/entron/entity-embedding-rossmann) of a similar [competition](https://www.kaggle.com/c/rossmann-store-sales/) on Kaggle.  I plan to use the embeddings format to plug into that type of model later.

This example code below deal with an example problem using a tiny matrix, just to get a handle on the options.

In [1]:
import pandas as pd
import numpy as np

%matplotlib inline
%config Completer.use_jedi = False


In [12]:
from keras.models import Model as KerasModel
from keras.layers import Input, Reshape, Dot, Add
from keras.layers.embeddings import Embedding
from keras import optimizers


I use a sample matrix, with `0` representing a missing value, exactly the same as in inspiration blog.

In [3]:
ds = pd.DataFrame([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 0],
    [0, 1, 5, 4],
])
ds.replace(to_replace=0,value=np.nan,inplace=True)
ds

0    1    2    3
0  5.0  3.0  NaN  1.0
1  4.0  NaN  NaN  1.0
2  1.0  1.0  NaN  5.0
3  1.0  NaN  NaN  NaN
4  NaN  1.0  5.0  4.0

Per Andrew Ng's [suggestion](https://www.coursera.org/learn/machine-learning/lecture/Adk8G/about), I could use the "mean normalization" step, but will not do for now for clarity.

In [4]:
col_means=ds.mean(axis=1)
ds_demeaned=ds.subtract(col_means,axis=0)


In [5]:
ds_unstacked=ds.unstack().reset_index()
ds_unstacked.rename(axis=1,mapper={'level_0':'column','level_1':'row',0:'truth'},inplace=True)

train=ds_unstacked.dropna()
train

column  row  truth
0        0    0    5.0
1        0    1    4.0
2        0    2    1.0
3        0    3    1.0
5        1    0    3.0
7        1    2    1.0
9        1    4    1.0
14       2    4    5.0
15       3    0    1.0
16       3    1    1.0
17       3    2    5.0
19       3    4    4.0

I will train 2-dimensional embeddings, meaning each level of `row` and `column` will be represented by 2 floating point numbers.  This is lower dimensionality than the `row` and `column` cardinality (4, and 5)

In [6]:
n_embed = 2
n_levels=train.nunique()
n_levels

column    4
row       5
truth     4
dtype: int64

The format of the Keras model matches that of the Rossmann competition winner's, so I that I can use the weights later in a larger model.

Note: I want to add regularization to the `Embedding()` layers later.

In [19]:
input_0 = Input(shape=(1,))
output_0 = Embedding(n_levels.column, n_embed, name='embedding_0')(input_0)
output_0 = Reshape(target_shape=(n_embed,))(output_0)
bias_0 = Embedding(n_levels.column, 1, name='bias_0')(input_0)
bias_0 = Reshape(target_shape=(1,))(bias_0)




input_1 = Input(shape=(1,))
output_1 = Embedding(n_levels.row, n_embed, name='embedding_1')(input_1)
bias_1 = Embedding(n_levels.row, 1, name='bias_1')(input_1)
bias_1 = Reshape(target_shape=(1,))(bias_1)



output_1 = Reshape(target_shape=(n_embed,))(output_1)

This is the core of the model, the single `Dot()` layer from Keras.

In [29]:
output_model = Dot(axes=-1, normalize=False)([output_0,output_1])
output_model = Add()([output_model,bias_0,bias_1])
model = KerasModel(inputs=[input_0,input_1], outputs=output_model)

This model expect a list of arrays as input, not sure if this format is very efficient, but don't know how to improve right now.

In [30]:
x=list(train.iloc[:,:2].values.T)
y=train.iloc[:,2]
x

[array([0, 0, 0, 0, 1, 1, 1, 2, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 2, 4, 4, 0, 1, 2, 4])]

Had to restart `model.fit()` several times to get a good result, usually final loss can go down to ~`0.01` with 2 dimensions.

In [31]:
sgd = optimizers.SGD(lr=0.4, decay=1e-6, momentum=0.5, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd)
model.fit(x,y,epochs=10)

Epoch 1/10
12/12 [==============================] - 0s 21ms/step - loss: 3.4862e-06
Epoch 2/10
12/12 [==============================] - 0s 257us/step - loss: 2.5570e-06
Epoch 3/10
12/12 [==============================] - 0s 253us/step - loss: 1.7549e-06
Epoch 4/10
12/12 [==============================] - 0s 201us/step - loss: 1.1529e-06
Epoch 5/10
12/12 [==============================] - 0s 190us/step - loss: 7.3498e-07
Epoch 6/10
12/12 [==============================] - 0s 243us/step - loss: 4.5883e-07
Epoch 7/10
12/12 [==============================] - 0s 301us/step - loss: 2.8219e-07
Epoch 8/10
12/12 [==============================] - 0s 284us/step - loss: 1.7144e-07
Epoch 9/10
12/12 [==============================] - 0s 409us/step - loss: 1.0334e-07
Epoch 10/10
12/12 [==============================] - 0s 214us/step - loss: 6.1889e-08


I can look at the weights, they don't seem to get excessively large without regularization right now.

In [33]:
model.get_layer('embedding_0').get_weights()[0]

array([[ 0.37729362, -1.35493934],
       [-0.50048554, -0.75053149],
       [ 0.34580427,  0.35050642],
       [-0.23149863,  1.5584656 ]], dtype=float32)

In [34]:
model.get_layer('embedding_1').get_weights()[0]

array([[-0.03072784, -1.26866412],
       [ 0.21787579, -0.87340105],
       [-0.48374251,  1.38260567],
       [-0.03108268,  0.02778644],
       [ 0.53025532,  0.83116722]], dtype=float32)

I will predict and compare to the true values.  Note the predicted matrix does not have any missing, allowing us to achieve the goal of the competition.

In [35]:
ds_unstacked['predicted']=model.predict(list(ds_unstacked.iloc[:,:2].values.T))
ds_unstacked.predicted=ds_unstacked.predicted.apply(lambda x: round(x,2))

ds_unstacked.pivot_table(values=['predicted','truth'],index='row',columns='column')

predicted                   truth               
column         0     1     2     3     0    1    2    3
row                                                    
0           5.00  3.00  4.21  1.00   5.0  3.0  NaN  1.0
1           4.00  2.02  3.88  1.00   4.0  NaN  NaN  1.0
2           1.00  1.00  4.75  5.00   1.0  1.0  NaN  5.0
3           1.00 -0.22  2.42  0.78   1.0  NaN  NaN  NaN
4           2.22  1.00  5.00  4.00   NaN  1.0  5.0  4.0

## Conclusion
I can train embeddings for item-item combinations, even with some combinations missing.  The embedding layers can be used later in larger model, or weights can be continuous variables in other models.